spring:
  application:
    name: mmorpg-platform-api
  datasource:
    login:
      url: ${LOGIN_DB_URL}
      username: ${LOGIN_DB_USER}
      password: ${LOGIN_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 4000

custom:
  security:
    regexp:
      user-name: "^[a-zA-Z0-9]+$"