spring:
  application:
    name: mmorpg-platform-api
  datasource:
    login:
      url: ${LOGIN_DB_URL}
      username: ${LOGIN_DB_USER}
      password: ${LOGIN_DB_PASS}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 4000