spring:
  application:
    name: mmorpg-platform-api
  datasource:
    web:
      url: ${WEB_DB_URL}
      username: ${WEB_DB_USER}
      password: ${WEB_DB_PASS}
      driver-class-name: com.mysql.cj.jdbc.Driver
    login:
      url: ${LOGIN_DB_URL}
      username: ${LOGIN_DB_USER}
      password: ${LOGIN_DB_PASS}
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate

server:
  port: 4000
  forward-headers-strategy: native

jwt:
  secret: ${JWT_SECRET_KEY}