spring:
  application:
    name: mmorpg-platform-api
  datasource:
    web:
      url: ${WEB_DB_URL:jdbc:mysql://localhost:3306/l2_web?useSSL=false&serverTimezone=UTC}
      username: ${WEB_DB_USER:root}
      password: ${WEB_DB_PASS:ehc6001}
    login:
      url: ${LOGIN_DB_URL:jdbc:mysql://localhost:3306/l2_login?useSSL=false&serverTimezone=UTC}
      username: ${LOGIN_DB_USER:root}
      password: ${LOGIN_DB_PASS:ehc6001}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 4000

jwt:
  secret: ${JWT_SECRET_KEY:8fK2vW9xZ4mQ7tN1sJ5cR3vF8xY0eU2iO6pW1bE9zAs=}