spring:
  application:
    name: mmorpg-platform-api
  datasource:
    web:
      url: ${WEB_DB_URL}
      username: ${WEB_DB_USER}
      password: ${WEB_DB_PASS}
      driver-class-name: com.mysql.cj.jdbc.Driver
    login:
      url: ${LOGIN_DB_URL}
      username: ${LOGIN_DB_USER}
      password: ${LOGIN_DB_PASS}
      driver-class-name: com.mysql.cj.jdbc.Driver
    game:
      url: ${GAME_DB_URL}
      username: ${GAME_DB_USER}
      password: ${GAME_DB_PASS}
      driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
  jwt:
    secret: ${JWT_SECRET_KEY:8fK2vW9xZ4mQ7tN1sJ5cR3vF8xY0eU2iO6pW1bE9zAs=}

server:
  port: 4000
  forward-headers-strategy: native
