spring:
  application:
    name: mmorpg-platform-api
  datasource:
    login:
      url: ${LOGIN_DB_URL:jdbc:mysql://mysql-l2_game:3306/gk_web_user?useSSL=false&serverTimezone=UTC}
      username: ${LOGIN_DB_USER:gk_web_user}
      password: ${LOGIN_DB_PASS:Abc1234}
  jpa:
    hibernate:
      ddl-auto: update
server:
  port: 4000

jwt:
  secret: ${JWT_SECRET_KEY:8fK2vW9xZ4mQ7tN1sJ5cR3vF8xY0eU2iO6pW1bE9zAs=}